name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Tailwind CSS and PostCSS
        run: |
          npm install -D tailwindcss@latest postcss@latest autoprefixer@latest

      - name: Create Tailwind config
        run: |
          cat > tailwind.config.js << EOL
          /** @type {import('tailwindcss').Config} */
          module.exports = {
            content: [
              './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
              './src/components/**/*.{js,ts,jsx,tsx,mdx}',
              './src/app/**/*.{js,ts,jsx,tsx,mdx}',
            ],
            theme: {
              extend: {
                fontFamily: {
                  inter: ['var(--font-inter)'],
                  orbitron: ['var(--font-orbitron)'],
                },
              },
            },
            plugins: [],
          }
          EOL

      - name: Create PostCSS config
        run: |
          cat > postcss.config.js << EOL
          module.exports = {
            plugins: {
              tailwindcss: {},
              autoprefixer: {},
            },
          }
          EOL

      - name: Build Project
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /prompt
        run: |
          npm run build
          touch out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
